### ISSUE TITLE
Issue on running the HelloWorld alexa-skill-kit Sample from the Command Line

### ISSUE THREAD

**Issue by PrithiviRajG** [alexa/legacy-skill-samples-java#4]
I am trying to run Hello world alexa skill kit java sample from command line using this [documentation](https://developer.amazon.com/docs/custom-skills/deploy-a-sample-skill-as-a-web-service.html#h3_run_cmdline). I am able to build the jar successfully but I am getting the below exception on trying to run the sample with `mvn exec:java -Dexec.executable=”java” -DdisableRequestSignatureCheck=true` command

```
java.lang.ClassNotFoundException: Launcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ghost** [comment]
For anyone else who has come across the same issue as I did today.

The reason the Launcher class cannot be found is because it does not _currently_ exist in this repo. From what I can see it looks like the samples were moved from the alexa-skills-kit-java repo into this one but the Launcher class was not included. The latest version of alexa-skills-kit-java which _does_ include Launcher appears to be this one: [https://github.com/alexa/alexa-skills-kit-java/releases/tag/1.6.0](https://github.com/alexa/alexa-skills-kit-java/releases/tag/1.6.0).

Hopefully either this repo or the documentation will be updated as this is confusing to those of us new to alexa development.
