### ISSUE TITLE
Class not found: example.Hello: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by PrithiviRajG** [alexa/legacy-skill-samples-java#6]
I deployed the JAR as lambda function and executed Hello world from alexa simulator. I am getting below exception repeatedly 

`Class not found: example.Hello: java.lang.ClassNotFoundException`

I am just following the document and doing the same. I have been struck for running a sample JAVA app for 2 days.

Documents are outdated. This document https://developer.amazon.com/docs/custom-skills/use-the-alexa-skills-kit-samples.html want us to find the code inside samples/src/main/java in  [amzn/alexa-skills-kit-java repository](https://developer.amazon.com/docs/custom-skills/use-the-alexa-skills-kit-samples.html) but the repositories are changed significantly.

Please help me

**Comment by ghost** [comment]
Hi there, can you paste the stack trace you are seeing? It would help a lot to see where it's going wrong.

**Comment by superbrew** [comment]
I am having the same issue.

START RequestId: ffaff6e4-e827-11e7-a08e-87717612044e Version: $LATEST
Class not found: example.Hello: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: example.Hello
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

END RequestId: ffaff6e4-e827-11e7-a08e-87717612044e
REPORT RequestId: ffaff6e4-e827-11e7-a08e-87717612044e	Duration: 25.96 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 24 MB

**Comment by ghost** [comment]
In Lambda, under Function Code, where you specify Handler Info, instead of 'example.Hello', you need to replace that with your own Request Handler. 

This [link](https://github.com/alexa/skill-samples-java/tree/master/helloworld) shows how you would do that in AWS Lambda Setup instruction 9. In this example, handler info is 'com.amazon.asksdk.helloworld.HelloWorldSpeechletRequestStreamHandler' and that's what you would be replacing instead of 'example.Hello'

Let me know if you still have trouble!

**Comment by ghost** [comment]
Closing due to inactivity, please feel free to reopen if the issues persists!
